baseurl = "https://blog.foresta.me/"
languageCode = "jp"
countryCode = "ja"
title = "blog.foresta.me"

pygmentsCodeFences = true
pygmentsOptions = "nobackground=true"
pygmentsstyle = "github"
googleAnalytics = "UA-102975147-1"

[taxonomies]
category = "categories"
tag = "tags"

[Params]
author = "kazuki morita"
description = "日々の開発とかいろいろ"
noimage = "noimage.jpg"

[permalinks]
posts = "/posts/:filename/"
