baseurl = "https://blog.foresta.me/"
languageCode = "jp"
title = "blog.foresta.me"

uglyurls = true

pygmentsCodeFences = true
pygmentsOptions = "linenos=table,nobackground=true"

[taxonomies]
category = "categories"
tag = "tags"

[Params]
author = "kazuki morita"
description = "日々の開発とかいろいろ"
